on respawn:
    set {_player} to player
    # Отримати випадкове повідомлення з death_messages.txt
    wait 2 seconds
    set {_randomDeathMessage} to getRandomDeathMessage()
    
    # Повідомлення від Геробрина після смерті
    set {_herobrinePrefix} to "&c&kA &r" + getRandomHerobrinePrefix() + " &7» &r"
    broadcast {_herobrinePrefix} + {_randomDeathMessage}
    
    make console execute command "discordsrv broadcast %{_herobrinePrefix} + {_randomDeathMessage}%"
    
  