on chat:
  if message is "Bedge":
    if "%world of player%" is "world_nether":
      # Trigger the explosion effect
      create explosion of force 5 at location of player
      send "&cНе варто намагатися спати в Незері!" to player


on chat:
  if message is "Bedge":
    if "%world of player%" is "world_end":
      # Trigger the explosion effect
      create explosion of force 5 at location of player
      send "&cНе варто намагатися спати в Енді!" to player
   