every 6 ticks:
    loop all players:
        if loop-player is not null:
            if loop-player's tool is a amethyst shard:
                set {_y} to floor(loop-player's y-coordinate)
                set {_yaw} to floor(yaw of loop-player)
                set {_pitch} to floor(pitch of loop-player)
                set {_coords} to "Висота: %{_y}%"
                send action bar "%{_coords}%" to loop-player
